
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           12803
     no. of nonzeroes in lower triangle of a =          163698
     no. of nonzeroes in the factor l        =          360326
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =             803
     maximum order of a front matrix         =              89
     maximum size of a front matrix          =            4005
     maximum size of a front trapezoid       =            2628
     METIS reordering method used 
     no. of floating point ops for factor    =      7.0225D+06
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           12659
     number of negative pivots               =             144
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =             130
     number of 2x2 pivots                    =               6
     number of delayed pivots                =               0
     number of deferred pivots               =              81
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               2
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.004767
     time (cpu & wall) for ordering          =        0.031250        0.020824
     time (cpu & wall) for other matrix prep =        0.000000        0.008093
     time (cpu & wall) for value input       =        0.000000        0.013164
     time (cpu & wall) for matrix distrib.   =        0.015625        0.023295
     time (cpu & wall) for numeric factor    =        0.140625        0.179078
     computational rate (gflops) for factor  =        0.049938        0.039215
     time (cpu & wall) for numeric solve     =        0.015625        0.005808
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        124123.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        131072.        1. MB        124123.        1. MB


  Total Solver Memory allocated              =       25.571 MB
